spring:
  application:
    name: ai_lms-server
  datasource:
    url: jdbc:mysql://localhost:3306/ai_lms
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    path: /